-- BUG:
-- opening the toggle tags menu in netrw causes the window to persist
return {
  -- {
  --   "cbochs/grapple.nvim",
  --   opts = {
  --     scope = "git", -- also try out "git_branch"
  --     icons = false, -- setting to "true" requires "nvim-web-devicons"
  --     status = false,
  --   },
  --   keys = {
  --     { "<leader>a", "<cmd>Grapple toggle<cr>", desc = "Tag a file" },
  --     { "<C-e>", "<cmd>Grapple toggle_tags<cr>", desc = "Toggle tags menu" },
  --
  --     { "<C-h>", "<cmd>Grapple select index=1<cr>", desc = "Select first tag" },
  --     { "<C-j>", "<cmd>Grapple select index=2<cr>", desc = "Select second tag" },
  --     { "<C-k>", "<cmd>Grapple select index=3<cr>", desc = "Select third tag" },
  --     { "<C-l>", "<cmd>Grapple select index=4<cr>", desc = "Select fourth tag" },
  --   },
  -- },
}
